import { readFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

export const root = dirname(dirname(fileURLToPath(import.meta.url)))
const tokensDir = join(root, 'tokens')

export const THEMES = ['dark', 'light']
export const EXTENSION_KEY = 'com.strata'
export const REDUCED_MOTION_QUERY = '(prefers-reduced-motion: reduce)'

const HEADER = 'Generated by scripts/build.mjs from tokens/*.json. Do not edit by hand.'

const SOURCES = {
  primitive: ['primitives.json'],
  semantic: ['semantic.shared.json', 'semantic.dark.json', 'semantic.light.json'],
  component: ['components.json'],
  domain: ['domain.json'],
}

const ALIAS = /^\{([^{}]+)\}$/
const HEX_DIGIT = /[0-9a-fA-F]/

async function readJson(name) {
  return JSON.parse(await readFile(join(tokensDir, name), 'utf8'))
}

function collect(tree, layer, file, into) {
  const walk = (node, path, inheritedType) => {
    const type = node.$type ?? inheritedType
    if ('$value' in node) {
      if (!type) throw new Error(`${file}: token "${path.join('.')}" has no $type`)
      into.push({
        path: path.join('.'),
        segments: path,
        type,
        value: node.$value,
        description: node.$description,
        extensions: node.$extensions?.[EXTENSION_KEY] ?? {},
        layer,
        file,
      })
      return
    }
    for (const [key, child] of Object.entries(node)) {
      if (key.startsWith('$')) continue
      walk(child, [...path, key], type)
    }
  }
  walk(tree, [], undefined)
}

function buildTable(tokens, label) {
  const table = new Map()
  for (const token of tokens) {
    if (table.has(token.path)) {
      throw new Error(`${label}: duplicate token "${token.path}" (${token.file})`)
    }
    table.set(token.path, token)
  }
  return table
}

const kebab = (segment) => segment.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase()
export const variableName = (token) => `--${token.segments.map(kebab).join('-')}`

export function aliasTarget(value, table, from) {
  const match = typeof value === 'string' ? ALIAS.exec(value) : null
  if (!match) return null
  const target = table.get(match[1])
  if (!target) throw new Error(`"${from.path}" references unknown token "${match[1]}"`)
  return target
}

function followAlias(token, table) {
  const seen = new Set([token.path])
  let current = token
  for (;;) {
    const target = aliasTarget(current.value, table, current)
    if (!target) return current
    if (seen.has(target.path)) throw new Error(`Circular alias at "${target.path}"`)
    if (target.type !== token.type) {
      throw new Error(`"${current.path}" (${token.type}) aliases "${target.path}" (${target.type})`)
    }
    seen.add(target.path)
    current = target
  }
}

function fontFamily(value) {
  return [value]
    .flat()
    .map((name) => (/\s/.test(name) ? `'${name}'` : name))
    .join(', ')
}

function cssString(value) {
  const chars = [...value]
  let out = ''
  chars.forEach((char, index) => {
    const code = char.codePointAt(0)
    if (char === '\\' || char === "'") {
      out += `\\${char}`
    } else if (code < 0x20 || code > 0x7e) {
      const next = chars[index + 1]
      out += `\\${code.toString(16)}${next !== undefined && HEX_DIGIT.test(next) ? ' ' : ''}`
    } else {
      out += char
    }
  })
  return `'${out}'`
}

function shadowLayer(layer, render) {
  return [layer.offsetX, layer.offsetY, layer.blur, layer.spread, render(layer.color)].join(' ')
}

function cssLiteral(type, value, renderNested) {
  switch (type) {
    case 'color':
    case 'dimension':
    case 'duration':
    case 'number':
    case 'fontWeight':
    case 'strokeStyle':
    case 'keyword':
      return String(value)
    case 'string':
      return cssString(value)
    case 'cubicBezier':
      return `cubic-bezier(${value.join(', ')})`
    case 'fontFamily':
      return fontFamily(value)
    case 'shadow':
      return [value]
        .flat()
        .map((layer) => shadowLayer(layer, renderNested))
        .join(', ')
    default:
      throw new Error(`Unsupported $type "${type}"`)
  }
}

function cssValue(token, table) {
  const target = aliasTarget(token.value, table, token)
  if (target) return `var(${variableName(target)})`
  return cssLiteral(token.type, token.value, (nested) => {
    const nestedTarget = aliasTarget(nested, table, token)
    return nestedTarget ? `var(${variableName(nestedTarget)})` : String(nested)
  })
}

function resolvedValue(token, table) {
  const final = followAlias(token, table)
  if (final.type !== 'shadow') return final.value
  return [final.value].flat().map((layer) => {
    const nestedTarget = aliasTarget(layer.color, table, final)
    return { ...layer, color: nestedTarget ? followAlias(nestedTarget, table).value : layer.color }
  })
}

function declarations(tokens, table, indent) {
  return tokens
    .map((token) => `${indent}${variableName(token)}: ${cssValue(token, table)};`)
    .join('\n')
}

function assertThemeParity(dark, light) {
  const signature = (tokens) => new Map(tokens.map((token) => [token.path, token.type]))
  const a = signature(dark)
  const b = signature(light)
  for (const [path, type] of a) {
    if (b.get(path) !== type)
      throw new Error(`Theme mismatch: "${path}" missing or retyped in light`)
  }
  for (const path of b.keys()) {
    if (!a.has(path)) throw new Error(`Theme mismatch: "${path}" missing in dark`)
  }
}

function assertLiteralColorsOnlyInPrimitives(tokens, table) {
  for (const token of tokens) {
    if (token.layer === 'primitive' || aliasTarget(token.value, table, token)) continue
    const literals =
      token.type === 'color'
        ? [token.value]
        : token.type === 'shadow'
          ? [token.value].flat().map((layer) => layer.color)
          : []
    for (const literal of literals) {
      if (!aliasTarget(literal, table, token)) {
        throw new Error(
          `"${token.path}" (${token.file}) uses a literal color; colors live in primitives`,
        )
      }
    }
  }
}

function assertReducedMotionOverrides(tokens) {
  for (const token of tokens) {
    const reduced = token.extensions.reducedMotion
    if (reduced === undefined) continue
    if (token.layer !== 'semantic' || token.file !== 'semantic.shared.json') {
      throw new Error(`"${token.path}": reducedMotion is only supported in semantic.shared.json`)
    }
    if (typeof reduced !== 'string' || ALIAS.test(reduced)) {
      throw new Error(`"${token.path}": reducedMotion must be a literal CSS value`)
    }
  }
}

export async function loadTokens() {
  const tokensByFile = {}
  for (const [layer, files] of Object.entries(SOURCES)) {
    for (const file of files) {
      const collected = []
      collect(await readJson(file), layer, file, collected)
      tokensByFile[file] = collected
    }
  }

  const primitive = tokensByFile['primitives.json']
  const component = tokensByFile['components.json']
  const domain = tokensByFile['domain.json']
  const shared = tokensByFile['semantic.shared.json']
  const byTheme = {}
  for (const theme of THEMES) byTheme[theme] = tokensByFile[`semantic.${theme}.json`]
  assertThemeParity(byTheme.dark, byTheme.light)
  assertReducedMotionOverrides(shared)

  const tokensByTheme = {}
  const tables = {}
  for (const theme of THEMES) {
    tokensByTheme[theme] = [...primitive, ...shared, ...byTheme[theme], ...component, ...domain]
    tables[theme] = buildTable(tokensByTheme[theme], theme)
    assertLiteralColorsOnlyInPrimitives(tokensByTheme[theme], tables[theme])
  }

  const layers = {
    primitive,
    semantic: [...shared, ...byTheme.dark],
    component,
    domain,
  }
  const names = new Map()
  for (const token of Object.values(layers).flat()) {
    const name = variableName(token)
    if (names.has(name))
      throw new Error(`CSS variable collision: ${name} (${names.get(name)}, ${token.path})`)
    names.set(name, token.path)
  }

  return {
    primitive,
    shared,
    byTheme,
    component,
    domain,
    tokensByTheme,
    layers,
    variableCount: names.size,
    tableFor: (theme) => tables[theme],
    resolve: (theme, path) => {
      const token = tables[theme].get(path)
      if (!token) throw new Error(`Unknown token "${path}"`)
      return resolvedValue(token, tables[theme])
    },
  }
}

export function buildCss(model) {
  const { primitive, shared, byTheme, component, domain, tableFor } = model
  const rootTable = tableFor('dark')
  const blocks = [
    `/* ${HEADER} */`,
    [':root {', declarations([...primitive, ...shared], rootTable, '  '), '}'].join('\n'),
  ]

  const themeBlock = (selector, theme, indent = '') =>
    [
      `${indent}${selector} {`,
      `${indent}  color-scheme: ${theme};`,
      declarations(byTheme[theme], tableFor(theme), `${indent}  `),
      `${indent}}`,
    ].join('\n')

  blocks.push(themeBlock(":root,\n[data-theme='dark']", 'dark'))
  blocks.push(
    [
      '@media (prefers-color-scheme: light) {',
      themeBlock(':root:not([data-theme])', 'light', '  '),
      '}',
    ].join('\n'),
  )
  blocks.push(themeBlock("[data-theme='light']", 'light'))
  blocks.push(
    [':root,\n[data-theme] {', declarations([...component, ...domain], rootTable, '  '), '}'].join(
      '\n',
    ),
  )

  const reduced = shared.filter((token) => token.extensions.reducedMotion !== undefined)
  if (reduced.length > 0) {
    const lines = reduced
      .map((token) => `    ${variableName(token)}: ${token.extensions.reducedMotion};`)
      .join('\n')
    blocks.push(`@media ${REDUCED_MOTION_QUERY} {\n  :root {\n${lines}\n  }\n}`)
  }
  return `${blocks.join('\n\n')}\n`
}

export function buildJson(model) {
  const { tokensByTheme, tableFor } = model
  const output = {
    $description: HEADER,
  }
  for (const theme of THEMES) {
    const table = tableFor(theme)
    const tree = {}
    for (const token of tokensByTheme[theme]) {
      let group = tree
      for (const segment of token.segments.slice(0, -1)) group = group[segment] ??= {}
      const entry = { $type: token.type, $value: resolvedValue(token, table) }
      if (token.description) entry.$description = token.description
      const alias =
        typeof token.value === 'string' && ALIAS.test(token.value) ? token.value : undefined
      entry.$extensions = {
        [EXTENSION_KEY]: {
          layer: token.layer,
          ...(alias ? { alias } : {}),
          ...(token.extensions.reducedMotion === undefined
            ? {}
            : { reducedMotion: token.extensions.reducedMotion }),
        },
      }
      group[token.segments.at(-1)] = entry
    }
    output[theme] = tree
  }
  return `${JSON.stringify(output, null, 2)}\n`
}

export function buildTypes(model) {
  const lines = [`// ${HEADER}`, '']
  for (const [name, tokens] of Object.entries(model.layers)) {
    lines.push(`export const ${name}Variables = {`)
    for (const token of tokens) lines.push(`  '${token.path}': '${variableName(token)}',`)
    lines.push('} as const', '')
  }
  const names = Object.keys(model.layers)
  lines.push('export const tokenVariables = {')
  for (const name of names) lines.push(`  ...${name}Variables,`)
  lines.push('} as const', '')
  for (const name of names) {
    const type = `${name[0].toUpperCase()}${name.slice(1)}TokenPath`
    lines.push(`export type ${type} = keyof typeof ${name}Variables`)
  }
  lines.push(
    'export type TokenPath = keyof typeof tokenVariables',
    'export type CssVariableName = (typeof tokenVariables)[TokenPath]',
    '',
    `export const themeNames = [${THEMES.map((theme) => `'${theme}'`).join(', ')}] as const`,
    'export type ThemeName = (typeof themeNames)[number]',
    '',
  )
  return lines.join('\n')
}
